### ISSUE TITLE
FairMQDevice segmentation violation

### ISSUE THREAD

**Issue by matthiasrichter** [FairRootGroup/FairRoot#542]
I accidentally specified a channel address for a device with out the protocol, just the port number. This is correctly detected at device start

```bash
[ERROR] invalid channel address: "55000" (missing protocol specifier?)
```

But then there is a segmentation violation in `FairMQDevice::LogSocketRates()`

```bash
Thread 5 (Thread 0x7f643aa2d700 (LWP 19593)):
#0  0x00007f645e96a51b in __GI___waitpid (pid=19598, stat_loc=stat_loc
entry=0x7f643aa2a180, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007f645e8e3fbb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007f6457cdd204 in TUnixSystem::StackTrace() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/ROOT/v6-08-02_O2-3/lib/libCore.so.6.08
#3  0x00007f6457cdfb5c in TUnixSystem::DispatchSignals(ESignals) () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/ROOT/v6-08-02_O2-3/lib/libCore.so.6.08
#4  <signal handler called>
#5  0x00007f645f5a8d63 in FairMQDevice::LogSocketRates() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/FairRoot/5ed20b7-2/lib/libFairMQ.so
#6  0x00007f645f23fc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f64602446ba in start_thread (arg=0x7f643aa2d700) at pthread_create.c:333
#8  0x00007f645e9a582d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f645cfed700 (LWP 19561)):
#0  0x00007f645e9a5e23 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f645e00c01c in zmq::epoll_t::loop() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.so.5
#2  0x00007f645e03710a in thread_routine () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.so.5
#3  0x00007f64602446ba in start_thread (arg=0x7f645cfed700) at pthread_create.c:333
#4  0x00007f645e9a582d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f645d7ee700 (LWP 19560)):
#0  0x00007f645e9a5e23 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f645e00c01c in zmq::epoll_t::loop() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.so.5
#2  0x00007f645e03710a in thread_routine () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/ZeroMQ/v4.1.5-1/lib/libzmq.so.5
#3  0x00007f64602446ba in start_thread (arg=0x7f645d7ee700) at pthread_create.c:333
#4  0x00007f645e9a582d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f645dfef700 (LWP 19559)):
#0  0x00007f645e96a51b in __GI___waitpid (pid=19599, stat_loc=stat_loc
entry=0x7f645dfebe00, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007f645e8e3fbb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x00007f6457cdd204 in TUnixSystem::StackTrace() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/ROOT/v6-08-02_O2-3/lib/libCore.so.6.08
#3  0x00007f6457cdfb5c in TUnixSystem::DispatchSignals(ESignals) () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/ROOT/v6-08-02_O2-3/lib/libCore.so.6.08
#4  <signal handler called>
#5  0x00007f645f597bd1 in FairMQChannel::CheckCompatibility(std::vector<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> >, std::allocator<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> > > >&) const () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/FairRoot/5ed20b7-2/lib/libFairMQ.so
#6  0x00007f645f597d71 in FairMQChannel::Send(std::vector<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> >, std::allocator<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> > > >&) const () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/FairRoot/5ed20b7-2/lib/libFairMQ.so
#7  0x00007f645f8ce2ff in ALICE::HLT::WrapperDevice::Run() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/O2/dev-1/lib/libaliceHLTwrapper.so
#8  0x00007f645f5ac9ee in FairMQDevice::RunWrapper() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/FairRoot/5ed20b7-2/lib/libFairMQ.so
#9  0x00007f645f5b971f in FairMQFSM::FairMQFSM_::Worker() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/FairRoot/5ed20b7-2/lib/libFairMQ.so
#10 0x00007f645f23fc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007f64602446ba in start_thread (arg=0x7f645dfef700) at pthread_create.c:333
#12 0x00007f645e9a582d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f6460845740 (LWP 19558)):
#0  0x00007f645e999b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f645f5a692a in FairMQDevice::InteractiveStateLoop() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/FairRoot/5ed20b7-2/lib/libFairMQ.so
#2  0x000000000040e5be in int runStateMachine<FairMQDevice>(FairMQDevice&, FairMQProgOptions&) ()
#3  0x00000000004085a1 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x00007f645f5a8d63 in FairMQDevice::LogSocketRates() () from /home/richter/src/alisw/sw/ubuntu1604_x86-64/FairRoot/5ed20b7-2/lib/libFairMQ.so
#6  0x00007f645f23fc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f64602446ba in start_thread (arg=0x7f643aa2d700) at pthread_create.c:333
#8  0x00007f645e9a582d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

===========================================================

```

**Comment by rbx** [comment]
This should be fixed now. @matthiasrichter could you please confirm?

**Comment by matthiasrichter** [comment]
I don't have the error in today's dev. Thanks, I'm closing the issue.
